### ISSUE TITLE
Angular production builds breaks the web worker

### ISSUE THREAD

**Issue by monocl-oskar** [cloudnc/observable-webworker#14]
(Re-describing #13 in a reproducible manner)

Repro repo with code and clear description of the problem: [https://github.com/monocl-oskar/observable-webworker-problem](https://github.com/monocl-oskar/observable-webworker-problem)

When web workers created with `observable-webworker` gets run through Angular's production build mangling, they get destroyed.

For instance, this:

```ts
import { DoWork, ObservableWorker } from 'observable-webworker';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

@ObservableWorker()
class HelloWorker implements DoWork<string, string> {
  public work(input$: Observable<string>): Observable<string> {
    return input$.pipe(
      map(message => {
        return 'Hello from observable webworker';
      }),
    );
  }
}
```

Gets mangled into this (ran through a beautifier):

```js
! function(e) {
    var t = {};

    function r(n) {
        if (t[n]) return t[n].exports;
        var o = t[n] = {
            i: n,
            l: !1,
            exports: {}
        };
        return e[n].call(o.exports, o, o.exports, r), o.l = !0, o.exports
    }
    r.m = e, r.c = t, r.d = function(e, t, n) {
        r.o(e, t) || Object.defineProperty(e, t, {
            enumerable: !0,
            get: n
        })
    }, r.r = function(e) {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }), Object.defineProperty(e, "__esModule", {
            value: !0
        })
    }, r.t = function(e, t) {
        if (1 & t && (e = r(e)), 8 & t) return e;
        if (4 & t && "object" == typeof e && e && e.__esModule) return e;
        var n = Object.create(null);
        if (r.r(n), Object.defineProperty(n, "default", {
                enumerable: !0,
                value: e
            }), 2 & t && "string" != typeof e)
            for (var o in e) r.d(n, o, (function(t) {
                return e[t]
            }).bind(null, o));
        return n
    }, r.n = function(e) {
        var t = e && e.__esModule ? function() {
            return e.default
        } : function() {
            return e
        };
        return r.d(t, "a", t), t
    }, r.o = function(e, t) {
        return Object.prototype.hasOwnProperty.call(e, t)
    }, r.p = "", r(r.s = "zAnl")
}({
    zAnl: function(e, t, r) {
        "use strict";
        r.r(t), Error, "function" == typeof Symbol && Symbol
    }
});
```

No trace of `'Hello from observable webworker'` or even `addEventListener` for the web worker.

**Comment by zakhenry** [comment]
Hey @monocl-oskar thanks for the clear repro, I will dig into this likely on the weekend. It's an interesting problem as I'm not getting the same result in the demo for this repo which is also an angular prod build.

**Comment by monocl-oskar** [comment]
Weird! Will be interesting to know the differences.

**Comment by zakhenry** [comment]
@monocl-oskar ok curiosity got the better of me, I've dug into it and the issue was suprisingly straight forward! https://github.com/monocl-oskar/observable-webworker-problem/pull/1/files

Basically what is happening is that the minification process in angular is seeing that class not being exported, causing the entire class to be stripped. I guess it isn't able to know that the decorator actually performs work.

So the solution either to simply export the class so the minifier doesn't delete it (needed anyway if you're going to write tests for it), or use the `runWorker` alternative to the decorator.

As this is an easy mistake to make and unexpected that it only happens in a prod build I'll update the readme to make this super clear.

Thanks again for the excellent repro, that made my life much easier 😁

**Comment by monocl-oskar** [comment]
Awesome! Thanks a lot for taking a look so fast!
